### PR TITLE
Update news.data.service.ts

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@yuvalbl can we close this one?

**Comment by yuvalbl** [comment]
@atalyaalon 
This way of versioning the API is an anti-pattern
see my comment here
https://github.com/hasadna/anyway-newsflash-infographics/issues/774

**Comment by atalyaalon** [comment]
@yuvalbl thanks, we'll handle this

**Comment by yuvalbl** [comment]
Agreed - no versioning required, only collaboration on API update

**Pull request closed without merging**
