### PR TITLE
646 use multi bar chart for count-by-accident-year

### PR DESCRIPTION
**Pull request by yuvalbl**
first step of #647
image

### CODE REVIEW

**Comment by chenmu10** [comment]
The order is reversed. 
We get:
0: {label_key: "fatal", value: 0}
1: {label_key: "severe", value: 1}
2: {label_key: "light", value: 0} 
from BE.
If the ordering will change to ` light->fatal` it will solve it.
@BarVolunteering 

or we can change in GenericBarChart.tsx line 91:
```
  let yLabels = data ? Object.keys(data[0]) : [];
  yLabels.splice(0, 1);
  yLabels = yLabels.reverse();
```

**Comment by BarVolunteering** [comment]
@chenmu10 I can change it, but it will take some time as i have some issues/PRs that are in progress and i need to complete first.
Do you what me to do it?

**Comment by chenmu10** [comment]
Yes, thank you. 
@yuvalbl @atalyaalon @danielsh28 let me know if you see an issue with that.

**Review by chenmu10 — CHANGES_REQUESTED** [review]
Issues with ordering - needs to be addressed on BE/FE.

**Comment by BarVolunteering** [comment]
@chenmu10 Ordering is on BE stg, i created PR to prod
https://github.com/hasadna/anyway/pull/2168

**Pull request merged**
