### PR TITLE
[Refactor-650] add names to thank you list

### PR DESCRIPTION
**Pull request by daniel-ilan**
This is how it looks after adding the names
image

### CODE REVIEW

**Review by yuvalbl — APPROVED** [review]

**Review by eidan66 — APPROVED** [review]

**Review by yuvalbl — CHANGES_REQUESTED** [review]
wait for design

**Review by SejoB — COMMENTED** [review]
resolve conflicts

**Comment by eidan66** [comment]
@daniel-ilan  Do you fix the conflict?
If not, i can help you with it.

**Comment by daniel-ilan** [comment]
Sorry if I misunderstood, I thought this PR should go through design before we make final changes. If that is not the case I will resolve all conflicts ASAP

**Pull request closed without merging**
