### PR TITLE
fix 586 social icons outline on focus was removed

### PR DESCRIPTION
**Pull request by adele-angel**
Added CSS property
#586

### CODE REVIEW

**Comment by SejoB** [comment]
What are the changes in package-lock.json?
Resolve conflicts

**Review by SejoB — COMMENTED** [review]
What are the changes in package-lock.json?
Resolve conflicts

**Comment by adele-angel** [comment]
> What are the changes in package-lock.json?
> Resolve conflicts

There isn't a change

**Comment by eidan66** [comment]
Hey @adele-angel  !
Do you check about the conflicts ? 
image

**Comment by yuvalbl** [comment]
replaced by #639

**Pull request closed without merging**
